### ISSUE TITLE
WES Support in Consonance

### ISSUE THREAD

**Issue by alex-hancock** [BD2KGenomics/consonance#2]
See issue in the [original repo](https://github.com/Consonance/consonance/issues/154).

**Comment by alex-hancock** [comment]
Command to build template WES webservice code:
`java -jar ~/analysis_core/swagger-codegen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i wes.json -l jaxrs`

**Comment by alex-hancock** [comment]
Implementation up for WES API! 

Command: `curl -H "Authorization: Bearer {token here}" http://alex.ucsc-cgp-dev.org:8080/wes/workflows`

Results:
```
INFO  [2017-09-20 21:08:34,915] io.swagger.wes.api.impl.Ga4ghApiServiceImpl: Hit WES API! Called Ga4ghApiServiceImpl.getServiceInfo()
34.210.135.214 - - [20/Sep/2017:21:08:34 +0000] "GET /wes/service-info HTTP/1.1" 200 57 "-" "curl/7.47.0" 8
INFO  [2017-09-20 21:09:03,815] io.swagger.wes.api.impl.Ga4ghApiServiceImpl: Hit WES API! Called Ga4ghApiServiceImpl.listWorkflows()
34.210.135.214 - - [20/Sep/2017:21:09:03 +0000] "GET /wes/workflows HTTP/1.1" 200 57 "-" "curl/7.47.0" 2
```

Now attaching WES API to Consonance infrastructure

**Comment by alex-hancock** [comment]
Progress on WES support will be centered on the endpoint implementation in [Ga4ghApiServiceImplementation.java](https://github.com/BD2KGenomics/consonance/blob/feature/wes-support/consonance-webservice/src/main/java/io/swagger/wes/api/impl/Ga4ghApiServiceImplementation.java). 

Implementations based on [this](https://github.com/common-workflow-language/workflow-service/blob/master/wes_service/arvados_wes.py) demo in CWL.

**Comment by achave11** [comment]
Refer #14 for progress in WES support.
