### ISSUE TITLE
WES Implementation

### ISSUE THREAD

**Issue by achave11** [BD2KGenomics/consonance#20]
https://github.com/achave11/consonance/blob/feature/abraham_WES_draft/consonance-webservice/src/main/java/io/swagger/wes/api/impl/Ga4ghApiServiceImpl.java

Working implementation of the endpoints, in milestone 2. Need to integrate the client in order to develop integration test. Delete functionality not yet developed.

┆Issue is synchronized with this [JIRA Epic](https://ucsc-cgl.atlassian.net/browse/CON-10)
┆Project Name: Consonance
┆Issue Number: CON-10

**Comment by cricketsloan** [comment]
Here is a pull request. https://github.com/Consonance/consonance/pull/161

**Comment by mikebaumann** [comment]
Who is the primary reviewer for this PR?
I think it should be either @wshands and/or @david4096, as they are identified as the collaborators for Connsonance, here:
https://ucsc-cgl.atlassian.net/wiki/spaces/DEV/pages/131432488/2018+-+Computational+Genomics+Platform+Process+Vision#id-2018-ComputationalGenomicsPlatformProcess&Vision-Consonance

**Comment by cricketsloan** [comment]
This is stalled by #30
