### ISSUE TITLE
Implement Service Info

### ISSUE THREAD

**Issue by alex-hancock** [BD2KGenomics/consonance#4]
Implement the [getServiceInfo()](https://github.com/BD2KGenomics/consonance/blob/feature/wes-support/consonance-webservice/src/main/java/io/swagger/wes/api/Ga4ghApiService.java) method in the Ga4ghApiService. 

Notes about Consonance implementation to follow. 

Notes about WES expectations of getServiceInfo() to follow.

**Comment by alex-hancock** [comment]
Basing Consonance WES based on the back-end in [this](https://github.com/common-workflow-language/workflow-service/blob/master/wes_service/arvados_wes.py#L26) demo implementation.

**Comment by alex-hancock** [comment]
Contacted Denis Yuen about proper implementations. Waiting to hear back to clarify proper format.

**Comment by kozbo** [comment]
Duplicate of #12, closing
